### ISSUE TITLE
ToDo: Checkout Plugin

### ISSUE THREAD

**Issue by hirbod** [FriendsOfREDAXO/shoppingcart#1]
Das AddOn stellt nur ein flexibles Warenkorb-Framework bereit, jedoch muss man sich um den Bezahlvorgang selbst kümmern. Ich werde das definitiv nicht umsetzen. Ich hab da zwar schon etwas mittels PayPal umgesetzt, aber es ist zu kundenspezifisch. Ich würde mir etwas smartes, flexibles wünschen, aber da muss sich jemand von FOR bereiterklären, Code beizusteuern.

- [ ] PayPal REST SDK mit Express Checkout (sehr einfach zu bauen)
- [ ] PayPal Plus
- [ ] Stripe
- [ ] Micropayment
- [ ] Rechnung (eigene Implementation)
- [ ] SEPA_Lastschrift (mit Mandatsgenerierung, Sepa.XML Erstellung als Export)

Das AddOn könnte ein super Shop-Plugin für REDAXO werden, da der Warenkorb sehr flexibel ist. Ich hab es selbst bereits mehrfach im Einsatz und bin zufrieden.

Jeder Bezahlprozess sollte ein eigenes Plugin sein und als PR übermittelt werden. Ich bezweifle, das jemals ein PR eingeht, aber ich darf ja noch hoffen.

Sollte das Plugin für das saubere Abarbeiten eine Datenbank nutzen müssen, sollte die install.php diese installieren. Die uninstall.php sollte jedoch niemals die erstelle Datenbank löschen. Das sollte zur Sicherheit bedacht werden.

Falls es keine PRs gibt, kann ich auch gerne für einen Job beauftragt werden. Ich würde mich aber über eine Beteiligung am Code eher freuen.

**Comment by hirbod** [comment]
Sehr interessant ist Omnipay, da es mit einer einzigen API gleich ~25 Anbieter unterstützt.
https://github.com/thephpleague/omnipay

Würde zum flexiblen System gut passen
